# ==============================================
#
#  Before starting the application
#  rename the application-local.yaml.template
#  to application-local.yaml
#  and add the specific local configurations
#
# ==============================================
spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    open-in-view: false
  profiles:
    include: base,local

